version: '3'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    command: celery --app tasks.task.celery worker --loglevel=info
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    container_name: conversion_toolDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
    depends_on:
      - redis

  redis:
    image: redis:6-alpine