version: '3'

services:
  app:
    container_name: app
    volumes:
      - ./app:/mnt/
    build: ./app
    working_dir: /app/
    command: bash -c './run_app.sh'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      FILES_FOLDER: /app/files
      PYTHONUNBUFFERED: 1
      EMAIL_DOMAIN: ${EMAIL_DOMAIN}
      EMAIL_API_KEY: ${EMAIL_API_KEY}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1000M
        reservations:
          cpus: '0.1'
          memory: 1000M
    depends_on:
      - conversion_tool_db

  conversion_tool_db:
    container_name: conversion_tool_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ConversionToolDB
      - POSTGRES_USER=postgres
    volumes:
      - ./app:/conversion_toolDB/
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1000M
        reservations:
          cpus: '0.1'
          memory: 1000M
  redis:
    image: redis
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1000M
        reservations:
          cpus: '0.1'
          memory: 1000M
